// Generated by nuxt-robots
import type { HookRobotsConfigContext, HookRobotsTxtContext, RobotsValue, RobotsContext, PatternMapValue } from '@nuxtjs/robots'

declare module 'nitropack' {
  interface NitroRouteRules {
    robots?: RobotsValue | {
      indexable: boolean
      rule: string
    }
  }
  interface NitroRouteConfig {
    robots?: RobotsValue | {
      indexable: boolean
      rule: string
    }
  }
  interface NitroRuntimeHooks {
    'robots:config': (ctx: HookRobotsConfigContext<import('h3').H3Event>) => void | Promise<void>
    'robots:robots-txt': (ctx: HookRobotsTxtContext<import('h3').H3Event>) => void | Promise<void>
  }
  interface NitroApp {
    _robots: {
      ctx: HookRobotsConfigContext<import('h3').H3Event>
      nuxtContentUrls?: Set<string>
    },
    _robotsRuleMatcher: (url: string) => any
    _robotsPatternMap?: Map<string, PatternMapValue>
  }
}

declare module 'nitropack/types' {
  interface NitroRouteRules {
    robots?: RobotsValue | {
      indexable: boolean
      rule: string
    }
  }
  interface NitroRouteConfig {
    robots?: RobotsValue | {
      indexable: boolean
      rule: string
    }
  }
  interface NitroRuntimeHooks {
    'robots:config': (ctx: HookRobotsConfigContext<import('h3').H3Event>) => void | Promise<void>
    'robots:robots-txt': (ctx: HookRobotsTxtContext<import('h3').H3Event>) => void | Promise<void>
  }
  interface NitroApp {
    _robots: {
      ctx: HookRobotsConfigContext<import('h3').H3Event>
      nuxtContentUrls?: Set<string>
    },
    _robotsRuleMatcher: (url: string) => any
    _robotsPatternMap?: Map<string, PatternMapValue>
  }
}

declare module 'h3' {
  interface H3EventContext {
    robots: RobotsContext
    robotsProduction?: RobotsContext
  }
}

export {}
