# Regenerates the local social preview and brand mark without external services.
Add-Type -AssemblyName System.Drawing
$assetRoot = Join-Path $PSScriptRoot '../public/images'
$ink = [System.Drawing.ColorTranslator]::FromHtml('#172523')
$blue = [System.Drawing.ColorTranslator]::FromHtml('#3056cf')
$paper = [System.Drawing.ColorTranslator]::FromHtml('#fafbf9')
$brushInk = [System.Drawing.SolidBrush]::new($ink)
$brushBlue = [System.Drawing.SolidBrush]::new($blue)
$brushWhite = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::White)
$bitmap = [System.Drawing.Bitmap]::new(1200, 630)
$graphics = [System.Drawing.Graphics]::FromImage($bitmap)
$graphics.SmoothingMode = 'AntiAlias'
$graphics.TextRenderingHint = 'AntiAliasGridFit'
$graphics.Clear($paper)
$small = [System.Drawing.Font]::new('Segoe UI', 16)
$title = [System.Drawing.Font]::new('Segoe UI', 54, [System.Drawing.FontStyle]::Bold)
$brand = [System.Drawing.Font]::new('Segoe UI', 24, [System.Drawing.FontStyle]::Bold)
$graphics.DrawString('Nexo Imports', $brand, $brushInk, 65, 50)
$graphics.DrawString('IMPORTADOR APPLE / CABA Y GBA', $small, $brushBlue, 70, 148)
$graphics.DrawString('Tu próximo Apple.', $title, $brushInk, 60, 205)
$graphics.DrawString('Más cerca.', $title, $brushBlue, 60, 295)
$graphics.DrawString('iPhone · iPad · Apple Watch · AirPods', $small, $brushInk, 70, 465)
$graphics.DrawString('Garantía oficial Apple. Atención personal Nexo.', $small, $brushInk, 70, 511)
$graphics.FillEllipse($brushBlue, 965, 178, 350, 350)
$graphics.FillEllipse($brushInk, 1040, 358, 220, 220)
$bitmap.Save((Join-Path $assetRoot 'og-default.png'), [System.Drawing.Imaging.ImageFormat]::Png)
$graphics.Dispose(); $bitmap.Dispose()
$logo = [System.Drawing.Bitmap]::new(512, 512)
$graphics = [System.Drawing.Graphics]::FromImage($logo)
$graphics.TextRenderingHint = 'AntiAliasGridFit'
$graphics.Clear($ink)
$logoFont = [System.Drawing.Font]::new('Segoe UI', 190, [System.Drawing.FontStyle]::Bold)
$graphics.DrawString('n', $logoFont, $brushWhite, 85, 53)
$arrowFont = [System.Drawing.Font]::new('Segoe UI Symbol', 100)
$graphics.DrawString('↗', $arrowFont, $brushWhite, 280, 30)
$logo.Save((Join-Path $assetRoot 'logo.png'), [System.Drawing.Imaging.ImageFormat]::Png)
$graphics.Dispose(); $logo.Dispose()
$small.Dispose(); $title.Dispose(); $brand.Dispose(); $logoFont.Dispose(); $arrowFont.Dispose()
$brushInk.Dispose(); $brushBlue.Dispose(); $brushWhite.Dispose()
